<?php include 'includes/header.php'?>
<section id="sap-document-archiving">
    <div class="container">
        <div class="center wow fadeInDown">
            <article>
                <h2>SAP<sup>&reg;</sup> Document Archiving</h2>
                <p class="lead"><strong>Document archiving</strong> focuses on three main components namely; Incoming documents (scanning), Outgoing documents (SAP<sup>&reg;</sup> generated invoices, notifications etc.) and <strong>Print lists</strong> (spools generated by reports).</p>
                <p class="lead">While many companies only implement incoming document archiving, ArcSystemSolutions presents and encourages this valuable functionality that SAP<sup>&reg;</sup> provides with the other two components. One of our clients used to print thousands of pages of financial month-end-reports each month and keep these hard copies for future reference; until we demonstrated the automated archiving of Print lists and the ease they could be retrieved. The cost saving on material, storage and time spent on retrieval was enormous.</p>
                <p class="lead"><strong>Outgoing document archiving</strong> is often overlooked, but has its place when for instance Smart Forms are used. During litigation proceeding, a company may be requested to produce an original document which was printed 5 years ago. The directors may have changed or even contact details. Reprinting this historic document now, will not reflect the true copy and may raise questions around authenticity and accuracy of the data. We therefore wish to keep a ‘snapshot’ of certain documents we produce from SAP<sup>&reg;</sup> and archive these for future reference.</p>
                <p class="lead"><strong>Incoming document archiving</strong> is a valuable tool and many SAP<sup>&reg;</sup> Partners have developed and refined, add- on solutions with Optical Character Recognition (OCR) functionality and automated workflow. Volumes and client budget will determine which solution we recommend to our clients and may even include going with the SAP<sup>&reg;</sup> standard, at no additional software costs.</p>
                <p class="lead">The importance of document archiving is firstly to move towards a paperless environment, leaving less of a footprint; secondly to be able to integrate documents with our SAP<sup>&reg;</sup> data and being able to view all details of an employee or supplier as a complete unit from one transaction; and thirdly the cost saving that goes with increasing retrieval performance and overall productivity.</p>
                <p class="lead">Please <a href="mailto:info@arcsystemsolutions.co.za?Subject=SAP%20Document%20Archiving">contact us</a> to discuss your SAP<sup>&reg;</sup> Document Archiving requirements.</p>
            </article>
        </div>
    </div>
</section>
<?php include 'includes/footer.php'?>
