<?php include 'includes/header.php'?>
<section id="terms">
    <div class="container">
        <div class="center wow fadeInDown">
            <article>
                <h2>Terms</h2>
                <p class="lead"><strong>ArcSystemSolutions Terms of Use</strong></p>
                <p class="lead">Your access to and use of this site is subject to the following terms and conditions and all applicable laws. By accessing and using this site, you accept the following terms and conditions, without limitation or qualification.</p>
                <p class="lead">Unless otherwise stated, the contents of this site including, but not limited to, the text and images contained herein and their arrangement are the property of ArcSystemSolutions. All trademarks used or referred to in this website are the property of their respective owners.</p>
                <p class="lead">Nothing contained in this site shall be construed as conferring by implication, estoppel, or otherwise, any license or right to any copyright, patent, trademark or other proprietary interest of ArcSystemSolutions or any third party. This site and the content provided in this site, including, but not limited to, graphic images, audio, video, html code, buttons, and text, may not be copied, reproduced, republished, uploaded, posted, transmitted, or distributed in any way, without the prior written consent of ArcSystemSolutions, except that you may download, display, and print one copy of the materials on any single computer solely for your personal, non-commercial use, provided that you do not modify the material in any way and you keep intact all copyright, trademark, and other proprietary notices.</p>
                <p class="lead">The information provided on this site is free of charge and for informational purposes only and does not create a business or professional services relationship between you and ArcSystemSolutions. Links on this site may lead to services or sites not operated by ArcSystemSolutions. No judgment or warranty is made with respect to such other services or sites and ArcSystemSolutions takes no responsibility for such other sites or services. A link to another site or service is not an endorsement of that site or service. Any use you make of the information provided on this site, or any site or service linked to by this site, is at your own risk.</p>
                <p class="lead">This site and its contents are provided "as is" and ArcSystemSolutions makes no representation or warranty of any kind with respect to this site or any site or service accessible through this site. In no event will ArcSystemSolutions be liable to any party for any direct, indirect, incidental, special, exemplary, consequential, or other damages (including, but not limited to, lost profits, business interruption, loss of programs or data) without regard to the form of action and whether in contract, tort, negligence, strict liability, or otherwise, arising out of or in connection with this site, any content on or accessed through this site or any site service linked to, or any copying, displaying, or use thereof.</p>
                <p class="lead">ArcSystemSolutions maintains this site in Pretoria, South Africa and you agree that these terms of use and any legal action or proceeding relating to this site shall be governed by the laws of South Africa without reference to its choice of law rules. If you attempt to bring any legal proceedings against ArcSystemSolutions you specifically acknowledge that ArcSystemSolutions is free to choose the jurisdiction of our preference as to where such action against us may be held. As you have agreed by using this site to choose the laws of South Africa to govern any such proceedings, we will probably choose to defend any such action in Pretoria and we can make this decision entirely as it suits us, without regard to where in the world you are located, or from where in the world you visited this site.</p>
                <p class="lead">You are responsible for complying with the laws of the jurisdiction from which you are accessing this site and you agree that you will not access or use the information on this site in violation of such laws. Unless expressly stated otherwise herein, any information submitted by you through this site shall be deemed non-confidential and non-proprietary. You represent that you have the lawful right to submit such information and agree that you will not submit any information unless you are legally entitled to do so. Because of the open nature of the Internet, we recommend that you not submit.</p>
            </article>
        </div>
    </div>
</section>
<?php include 'includes/footer.php'?>
